"""Explicitly registered MCP calls for the bounded cross-app loop.

The profile is trusted local configuration, never generated by the planner. A
model can only select an observed ref; it cannot edit server commands or args.
"""

from __future__ import annotations

import json
import re
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .executors.mcp import StdioMcpExecutor, StdioMcpServer
from .models import ActionCandidate, ActionReceipt, Channel, Risk, Verification
from .runtime import StepResult
from .verify import VerifierRegistry

_NAME = re.compile(r"^[A-Za-z][A-Za-z0-9_.-]{0,63}$")


@dataclass(frozen=True)
class McpCallOffer:
    ref: str
    server: str
    tool: str
    description: str
    arguments: dict[str, Any]
    expected: dict[str, Any]

    def to_dict(self) -> dict[str, Any]:
        return {
            "ref": self.ref, "capability": "mcp.call_tool", "channel": "mcp",
            "description": self.description, "server": self.server, "tool": self.tool,
        }

    def candidate(self, index: int) -> ActionCandidate:
        return ActionCandidate(
            id=f"option_{index}_mcp", channel=Channel.MCP,
            capability="mcp.call_tool", description=self.description,
            arguments={"server": self.server, "tool": self.tool,
                       "arguments": self.arguments},
            risk=Risk.EXTERNAL_SIDE_EFFECT, verifier="mcp.structured_result",
            expected={"structured_subset": self.expected}, intent=f"option_{index}",
        )


def _contains_expected(actual: Any, expected: Any) -> bool:
    if isinstance(expected, dict):
        return isinstance(actual, dict) and all(
            key in actual and _contains_expected(actual[key], value)
            for key, value in expected.items()
        )
    if isinstance(expected, list):
        return isinstance(actual, list) and len(actual) == len(expected) and all(
            _contains_expected(item, wanted) for item, wanted in zip(actual, expected, strict=True)
        )
    return actual == expected


def verify_mcp_structured_result(
    candidate: ActionCandidate, receipt: ActionReceipt
) -> Verification:
    structured = receipt.output.get("structured_content") if receipt.success else None
    expected = candidate.expected.get("structured_subset", {})
    passed = (
        receipt.success and isinstance(structured, dict)
        and _contains_expected(structured, expected)
    )
    return Verification(bool(passed), "mcp.structured_result", {
        "protocol_succeeded": receipt.success,
        "structured_result": isinstance(structured, dict),
        "expected_subset_matched": bool(passed),
    })


class McpToolSurface:
    """Finite, trusted-profile MCP offers under the ``m`` namespace."""

    namespace = "m"

    def __init__(self, server_name: str, server: StdioMcpServer,
                 offers: Sequence[McpCallOffer]) -> None:
        if not _NAME.fullmatch(server_name) or not 1 <= len(offers) <= 8:
            raise ValueError("MCP server name and 1-8 registered tools are required")
        if len({offer.ref for offer in offers}) != len(offers):
            raise ValueError("MCP offer refs must be unique")
        if any(
            offer.server != server_name or not _NAME.fullmatch(offer.tool)
            or offer.ref != f"m{index}"
            for index, offer in enumerate(offers)
        ):
            raise ValueError("MCP offers must bind to this server and sequential refs")
        self.offers = tuple(offers)
        self.executor = StdioMcpExecutor()
        self.executor.register_server(server_name, server, tools={offer.tool for offer in offers})
        self.supported_capabilities = frozenset({"mcp.call_tool"} | {
            f"mcp.{server_name}.{offer.tool}" for offer in offers
        })

    @classmethod
    def from_profile(cls, path: Path) -> McpToolSurface:
        """Load one explicitly trusted local profile; no model-authored commands."""
        if not path.is_file() or path.stat().st_size > 64_000:
            raise ValueError("MCP profile must be an existing file at most 64 KB")
        data = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(data, dict) or not isinstance(data.get("server"), dict):
            raise ValueError("MCP profile must contain one server object")
        server_data = data["server"]
        name, command, args = (
            server_data.get("name"), server_data.get("command"), server_data.get("args", [])
        )
        if (
            not isinstance(name, str) or not _NAME.fullmatch(name)
            or not isinstance(command, str) or not Path(command).is_absolute()
            or not Path(command).is_file()
            or not isinstance(args, list) or len(args) > 12
            or any(not isinstance(arg, str) or len(arg) > 500 for arg in args)
        ):
            raise ValueError("MCP server needs a name, existing absolute executable, and fixed args")
        raw_tools = data.get("tools")
        if not isinstance(raw_tools, list) or not 1 <= len(raw_tools) <= 8:
            raise ValueError("MCP profile must register 1-8 tools")
        offers = []
        for index, item in enumerate(raw_tools):
            if not isinstance(item, dict):
                raise ValueError("MCP tool entry must be an object")
            tool, description = item.get("name"), item.get("description")
            arguments, expected = item.get("arguments", {}), item.get("expected")
            if (
                not isinstance(tool, str) or not _NAME.fullmatch(tool)
                or not isinstance(description, str) or not 1 <= len(description) <= 240
                or not isinstance(arguments, dict) or not isinstance(expected, dict)
                or not expected
                or len(json.dumps(arguments, ensure_ascii=False)) > 4000
                or len(json.dumps(expected, ensure_ascii=False)) > 4000
            ):
                raise ValueError("MCP tool needs a name, description, and bounded JSON objects")
            offers.append(McpCallOffer(f"m{index}", name, tool, description, arguments, expected))
        return cls(name, StdioMcpServer(command, tuple(args)), offers)

    def reset(self) -> None:
        pass

    def close(self) -> None:
        pass

    def observe(self, history: Sequence[StepResult]) -> tuple[McpCallOffer, ...]:
        return self.offers

    def capture(self) -> tuple[McpCallOffer, ...]:
        return self.offers

    def validate(
        self, state: tuple[McpCallOffer, ...], ref: str, operation: Any, value: Any
    ) -> tuple[str, str, str]:
        if ref not in {offer.ref for offer in state} or operation != "invoke" or value:
            raise ValueError("MCP option must invoke one registered m: ref without arguments")
        return ref, "invoke", ""

    def compile(
        self, state: tuple[McpCallOffer, ...], ref: str, operation: str, value: str,
        subgoal: str, index: int,
    ) -> tuple[ActionCandidate, ...]:
        offer = next((offer for offer in state if offer.ref == ref), None)
        return (offer.candidate(index),) if offer is not None else ()

    def owns(self, candidate: ActionCandidate) -> bool:
        return candidate.capability == "mcp.call_tool"

    def execute(
        self, candidate: ActionCandidate, observation_id: str, decision_id: str
    ) -> ActionReceipt:
        return self.executor(candidate, observation_id, decision_id)

    def register_verifiers(self, registry: VerifierRegistry) -> None:
        registry.register("mcp.structured_result", verify_mcp_structured_result)
