"""Explicitly registered MCP calls for the bounded cross-app loop.

The profile is trusted local configuration, never generated by the planner. A
model may fill only bounded parameter fields declared by the caller; it cannot
edit server commands, tool names, or fixed arguments.
"""

from __future__ import annotations

import json
import re
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .executors.mcp import StdioMcpExecutor, StdioMcpServer
from .models import ActionCandidate, ActionReceipt, Channel, Risk, Verification
from .runtime import StepResult
from .verify import VerifierRegistry

_NAME = re.compile(r"^[A-Za-z][A-Za-z0-9_.-]{0,63}$")
_BLOCKED_PARAMETER = re.compile(r"(?:path|file|directory|folder|cwd|command|script|token|secret|key)", re.I)


@dataclass(frozen=True)
class McpCallOffer:
    ref: str
    server: str
    tool: str
    description: str
    arguments: dict[str, Any]
    expected: dict[str, Any]
    parameters: dict[str, dict[str, Any]] | None = None
    required: tuple[str, ...] = ()
    expected_from_arguments: dict[str, str] | None = None

    def to_dict(self) -> dict[str, Any]:
        state = {
            "ref": self.ref, "capability": "mcp.call_tool", "channel": "mcp",
            "description": self.description, "server": self.server, "tool": self.tool,
        }
        if self.parameters:
            state["parameters"] = self.parameters
            state["required"] = list(self.required)
        return state

    def candidate(self, index: int, generated: dict[str, Any] | None = None) -> ActionCandidate:
        arguments = {**self.arguments, **(generated or {})}
        expected = dict(self.expected)
        for output_key, argument_key in (self.expected_from_arguments or {}).items():
            expected[output_key] = arguments[argument_key]
        return ActionCandidate(
            id=f"option_{index}_mcp", channel=Channel.MCP,
            capability="mcp.call_tool", description=self.description,
            arguments={"server": self.server, "tool": self.tool,
                       "arguments": arguments},
            risk=Risk.EXTERNAL_SIDE_EFFECT, verifier="mcp.structured_result",
            expected={"structured_subset": expected}, intent=f"option_{index}",
        )


def _validate_parameters(offer: McpCallOffer, value: Any) -> tuple[str, dict[str, Any]]:
    parameters = offer.parameters or {}
    if not parameters:
        if value:
            raise ValueError("MCP option must invoke one registered m: ref without arguments")
        return "", {}
    if not isinstance(value, str) or not 1 <= len(value) <= 2000:
        raise ValueError("MCP parameters must be a bounded JSON object")
    try:
        generated = json.loads(value)
    except json.JSONDecodeError:
        raise ValueError("MCP parameters must be valid JSON") from None
    if not isinstance(generated, dict) or not set(offer.required) <= generated.keys():
        raise ValueError("MCP parameters omit required fields")
    if not generated.keys() <= parameters.keys():
        raise ValueError("MCP parameters contain an unregistered field")
    for key, item in generated.items():
        specification = parameters[key]
        kind = specification["type"]
        if kind == "string":
            if not isinstance(item, str) or not 1 <= len(item) <= specification["maxLength"]:
                raise ValueError("MCP string parameter is invalid")
        elif kind == "integer":
            if type(item) is not int or not 0 <= item <= specification["maximum"]:
                raise ValueError("MCP integer parameter is invalid")
        elif kind == "boolean" and type(item) is not bool:
            raise ValueError("MCP boolean parameter is invalid")
        if "enum" in specification and item not in specification["enum"]:
            raise ValueError("MCP parameter is outside its allowed values")
    return json.dumps(generated, sort_keys=True, ensure_ascii=False), generated


def _profile_parameters(item: dict[str, Any], fixed: dict[str, Any], expected: dict[str, Any]
                        ) -> tuple[dict[str, dict[str, Any]], tuple[str, ...], dict[str, str]]:
    parameters = item.get("parameters", {})
    required = item.get("required", [])
    expected_from = item.get("expected_from_arguments", {})
    if (
        not isinstance(parameters, dict) or len(parameters) > 8
        or not isinstance(required, list) or len(required) > 8
        or not isinstance(expected_from, dict) or len(expected_from) > 8
        or len(set(required)) != len(required)
        or any(not isinstance(key, str) for key in required)
    ):
        raise ValueError("MCP parameter declaration is invalid")
    if not set(required) <= parameters.keys() or parameters.keys() & fixed.keys():
        raise ValueError("MCP parameter names conflict with fixed arguments")
    for key, specification in parameters.items():
        if (
            not isinstance(key, str) or not _NAME.fullmatch(key)
            or _BLOCKED_PARAMETER.search(key)
            or not isinstance(specification, dict)
            or specification.get("type") not in {"string", "integer", "boolean"}
            or not specification.keys() <= {"type", "maxLength", "maximum", "enum"}
        ):
            raise ValueError("MCP parameter field is not allowed")
        kind = specification["type"]
        if kind == "string" and (
            type(specification.get("maxLength")) is not int
            or not 1 <= specification["maxLength"] <= 500
            or "maximum" in specification
        ):
            raise ValueError("MCP string parameter needs maxLength 1-500")
        if kind == "integer" and (
            type(specification.get("maximum")) is not int
            or not 0 <= specification["maximum"] <= 1000
            or "maxLength" in specification
        ):
            raise ValueError("MCP integer parameter needs maximum 0-1000")
        if kind == "boolean" and ("maxLength" in specification or "maximum" in specification):
            raise ValueError("MCP boolean parameter has unsupported bounds")
        enum = specification.get("enum")
        if enum is not None and (
            not isinstance(enum, list) or not 1 <= len(enum) <= 20
            or len({json.dumps(value, sort_keys=True) for value in enum}) != len(enum)
            or any(
                (kind == "string" and (not isinstance(value, str)
                    or not 1 <= len(value) <= specification["maxLength"]))
                or (kind == "integer" and (type(value) is not int
                    or not 0 <= value <= specification["maximum"]))
                or (kind == "boolean" and type(value) is not bool)
                for value in enum
            )
        ):
            raise ValueError("MCP parameter enum is invalid")
    if any(
        not isinstance(output_key, str) or not _NAME.fullmatch(output_key)
        or output_key in expected or not isinstance(argument_key, str)
        or argument_key not in parameters and argument_key not in fixed
        for output_key, argument_key in expected_from.items()
    ):
        raise ValueError("MCP expected_from_arguments is invalid")
    return parameters, tuple(required), expected_from


def _contains_expected(actual: Any, expected: Any) -> bool:
    if isinstance(expected, dict):
        return isinstance(actual, dict) and all(
            key in actual and _contains_expected(actual[key], value)
            for key, value in expected.items()
        )
    if isinstance(expected, list):
        return isinstance(actual, list) and len(actual) == len(expected) and all(
            _contains_expected(item, wanted) for item, wanted in zip(actual, expected, strict=True)
        )
    return actual == expected


def verify_mcp_structured_result(
    candidate: ActionCandidate, receipt: ActionReceipt
) -> Verification:
    structured = receipt.output.get("structured_content") if receipt.success else None
    expected = candidate.expected.get("structured_subset", {})
    passed = (
        receipt.success and isinstance(structured, dict)
        and _contains_expected(structured, expected)
    )
    return Verification(bool(passed), "mcp.structured_result", {
        "protocol_succeeded": receipt.success,
        "structured_result": isinstance(structured, dict),
        "expected_subset_matched": bool(passed),
    })


class McpToolSurface:
    """Finite, trusted-profile MCP offers under the ``m`` namespace."""

    namespace = "m"

    def __init__(self, server_name: str, server: StdioMcpServer,
                 offers: Sequence[McpCallOffer]) -> None:
        if not _NAME.fullmatch(server_name) or not 1 <= len(offers) <= 8:
            raise ValueError("MCP server name and 1-8 registered tools are required")
        if len({offer.ref for offer in offers}) != len(offers):
            raise ValueError("MCP offer refs must be unique")
        if any(
            offer.server != server_name or not _NAME.fullmatch(offer.tool)
            or offer.ref != f"m{index}"
            for index, offer in enumerate(offers)
        ):
            raise ValueError("MCP offers must bind to this server and sequential refs")
        self.offers = tuple(offers)
        self.executor = StdioMcpExecutor()
        self.executor.register_server(server_name, server, tools={offer.tool for offer in offers})
        self.supported_capabilities = frozenset({"mcp.call_tool"} | {
            f"mcp.{server_name}.{offer.tool}" for offer in offers
        })

    @classmethod
    def from_profile(cls, path: Path) -> McpToolSurface:
        """Load one explicitly trusted local profile; no model-authored commands."""
        if not path.is_file() or path.stat().st_size > 64_000:
            raise ValueError("MCP profile must be an existing file at most 64 KB")
        data = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(data, dict) or not isinstance(data.get("server"), dict):
            raise ValueError("MCP profile must contain one server object")
        server_data = data["server"]
        name, command, args = (
            server_data.get("name"), server_data.get("command"), server_data.get("args", [])
        )
        if (
            not isinstance(name, str) or not _NAME.fullmatch(name)
            or not isinstance(command, str) or not Path(command).is_absolute()
            or not Path(command).is_file()
            or not isinstance(args, list) or len(args) > 12
            or any(not isinstance(arg, str) or len(arg) > 500 for arg in args)
        ):
            raise ValueError("MCP server needs a name, existing absolute executable, and fixed args")
        raw_tools = data.get("tools")
        if not isinstance(raw_tools, list) or not 1 <= len(raw_tools) <= 8:
            raise ValueError("MCP profile must register 1-8 tools")
        offers = []
        for index, item in enumerate(raw_tools):
            if not isinstance(item, dict):
                raise ValueError("MCP tool entry must be an object")
            tool, description = item.get("name"), item.get("description")
            arguments, expected = item.get("arguments", {}), item.get("expected", {})
            if (
                not isinstance(tool, str) or not _NAME.fullmatch(tool)
                or not isinstance(description, str) or not 1 <= len(description) <= 240
                or not isinstance(arguments, dict) or not isinstance(expected, dict)
                or len(json.dumps(arguments, ensure_ascii=False)) > 4000
                or len(json.dumps(expected, ensure_ascii=False)) > 4000
            ):
                raise ValueError("MCP tool needs a name, description, and bounded JSON objects")
            parameters, required, expected_from = _profile_parameters(item, arguments, expected)
            if not expected and not expected_from:
                raise ValueError("MCP tool needs an expected result assertion")
            offers.append(McpCallOffer(
                f"m{index}", name, tool, description, arguments, expected,
                parameters, required, expected_from,
            ))
        return cls(name, StdioMcpServer(command, tuple(args)), offers)

    def reset(self) -> None:
        pass

    def close(self) -> None:
        pass

    def observe(self, history: Sequence[StepResult]) -> tuple[McpCallOffer, ...]:
        return self.offers

    def capture(self) -> tuple[McpCallOffer, ...]:
        return self.offers

    def validate(
        self, state: tuple[McpCallOffer, ...], ref: str, operation: Any, value: Any
    ) -> tuple[str, str, str]:
        offer = next((offer for offer in state if offer.ref == ref), None)
        if offer is None or operation != "invoke":
            raise ValueError("MCP option must invoke one registered m: ref")
        canonical, _ = _validate_parameters(offer, value)
        return ref, "invoke", canonical

    def compile(
        self, state: tuple[McpCallOffer, ...], ref: str, operation: str, value: str,
        subgoal: str, index: int,
    ) -> tuple[ActionCandidate, ...]:
        offer = next((offer for offer in state if offer.ref == ref), None)
        if offer is None:
            return ()
        _, generated = _validate_parameters(offer, value)
        return (offer.candidate(index, generated),)

    def owns(self, candidate: ActionCandidate) -> bool:
        return candidate.capability == "mcp.call_tool"

    def execute(
        self, candidate: ActionCandidate, observation_id: str, decision_id: str
    ) -> ActionReceipt:
        return self.executor(candidate, observation_id, decision_id)

    def register_verifiers(self, registry: VerifierRegistry) -> None:
        registry.register("mcp.structured_result", verify_mcp_structured_result)
